### PR TITLE
Use ldk and refactor wallet related methods

### LINKED ISSUE #71: Bump to latest secp256k1-zkp and use liquidjs-lib from npmjs
At the moment is broken otherwise

### PR DESCRIPTION
**Pull request by tiero**
This commit uses the lates ldk that pulls in async methods to unblind stuff.  I didn't see another way to import and uses `ldk` directly in the end.

* delete all Identity and Wallet stuff﻿, now impoted via ldk
* Introduce a simple `SwapTransaction` class that takes care of creating a swap transaction and producing pset, input & outpub blindin keys maps
* Make the Swap.request & Swap.accept method async, due the underlying change in how unblinding works

it closes #71

### CODE REVIEW

File: src/transaction.ts [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+    // We default to dumb coinselection. ie. se sort for value, first unspent found tha covers target, we use it.
+    const coinSelector = greedyCoinSelector();
+
+    const { selectedUtxos, changeOutputs } = coinSelector(
+      unspents,
+      [
+        {
+          value: amountToBeSent,
+          asset: assetToBeSent,
+          address: '',
```
Comment (tiero) [inline src/transaction.ts:54]: Is this the correct way to use it? I didn't see any other way for this use-case, wher I know the target amount&asset, but not the output, since is the other swap responder that will add it

Comment (tiero) [reply src/transaction.ts:54]: @louisinger

Comment (louisinger) [reply src/transaction.ts:54]: Yes, in fact the "targeted address" is not used by greedy coin selector. so it should work with and empty string

**Comment by tiero** [comment]
Some weird memory leak of the blech32 lib :/ 

```
      at process.<anonymous> (node_modules/blech32/src/blech32.js:8:1422)
  ●  process.exit called with "1"
```
